<?php
/**
 * Copyright 2023 Adobe
 * All Rights Reserved.
 */
// phpcs:disable Magento2.Templates.ThisInTemplate
// @codingStandardsIgnoreFile

/** @var \Magento\Sales\Block\Order\History $block */
/** @var $viewModel \Magento\OrderCancellationUi\ViewModel\Config */
$viewModel = $block->getViewModel();
?>
<?php $_orders = $block->getOrders(); ?>
<?= $block->getChildHtml('info') ?>
<?php if ($_orders && count($_orders)) : ?>
    <div class="table-wrapper orders-history">
        <table class="data table table-order-items history" id="my-orders-table">
            <caption class="table-caption"><?= $block->escapeHtml(__('Orders')) ?></caption>
            <thead>
            <tr>
                <th scope="col" class="col image"><?= $block->escapeHtml(__('Item')) ?></th>
                <th scope="col" class="col id"><?= $block->escapeHtml(__('Order #')) ?></th>
                <th scope="col" class="col date"><?= $block->escapeHtml(__('Date')) ?></th>
                <?= $block->getChildHtml('extra.column.header') ?>
                <th scope="col" class="col total"><?= $block->escapeHtml(__('Order Total')) ?></th>
                <th scope="col" class="col status"><?= $block->escapeHtml(__('Status')) ?></th>
                <th scope="col" class="col actions"><?= $block->escapeHtml(__('Action')) ?></th>
            </tr>
            </thead>
            <tbody>
            <?php foreach ($_orders as $_order) : ?>
                <tr>
                    <td data-th="<?= $block->escapeHtml(__('Item')) ?>" class="col image">
                        <?php
                        /** Get visible items only */
                        $items = $_order->getAllVisibleItems();

                        /** Get last item */
                        $lastItem = end($items);

                        if ($lastItem) {
                            try {
                                /** Load product */
                                $product = $lastItem->getProduct();
                                $productUrl = $product->getProductUrl();

                                /** Fallback if product is not loaded */
                                if (!$product || !$product->getId()) {
                                    $product = \Magento\Framework\App\ObjectManager::getInstance()
                                        ->get(\Magento\Catalog\Model\ProductRepository::class)
                                        ->getById($lastItem->getProductId());
                                }
                                $helperimg = $this->helper(\Setblue\Core\Helper\Data::class);
                                $imageUrl = $helperimg->getProductImageUrl($product, 'category_page_grid');
                                ?>
                                <a href="<?= $block->escapeUrl($productUrl) ?>" target="_blank">
                                    <img src="<?= $block->escapeUrl($imageUrl) ?>"
                                     alt="<?= $block->escapeHtml($lastItem->getName()) ?>"
                                     width="100" height="100" />
                                </a>
                                <?php
                            } catch (\Exception $e) {
                                echo __('No Image');
                            }
                        }
                        ?>
                    </td>
                    <td data-th="<?= $block->escapeHtml(__('Order #')) ?>" class="col id"><?= $block->escapeHtml($_order->getRealOrderId()) ?></td>
                    <td data-th="<?= $block->escapeHtml(__('Date')) ?>" class="col date"><?= /* @noEscape */ $block->formatDate($_order->getCreatedAt()) ?></td>
                    <?php $extra = $block->getChildBlock('extra.container'); ?>
                    <?php if ($extra) : ?>
                        <?php $extra->setOrder($_order); ?>
                        <?= $extra->getChildHtml() ?>
                    <?php endif; ?>
                    <td data-th="<?= $block->escapeHtml(__('Order Total')) ?>" class="col total"><?= /* @noEscape */ $_order->formatPrice($_order->getGrandTotal()) ?></td>
                    <td data-th="<?= $block->escapeHtml(__('Status')) ?>" class="col status"><span class="order-status <?php echo $_order->getStatusLabel();?>"><?= $block->escapeHtml($_order->getStatusLabel()) ?></span></td>
                    <td data-th="<?= $block->escapeHtml(__('Actions')) ?>" class="col actions">
                        <?php if ($_order->getStatus() != 'received'): ?>
                            <a href="<?= $block->escapeUrl($block->getViewUrl($_order)) ?>" class="action view">
                                <span><?= $block->escapeHtml(__('View Order')) ?></span>
                            </a>
                            <?php
                            /** @var \Setblue\Core\Helper\Data $helper */
                            $helper = $this->helper(\Setblue\Core\Helper\Data::class);
                            $orderIncrementId = $_order->getRealOrderId();
                            $trackingUrls = $helper->getTrackingByOrderIncrementId($orderIncrementId);
                            ?>

                            <?php if (!empty($trackingUrls) && is_array($trackingUrls)): ?>
                                <?php foreach ($trackingUrls as $trackingUrl): ?>
                                    <?php if (!empty($trackingUrl)): ?>
                                        <a href="<?= $block->escapeUrl($trackingUrl) ?>" target="_blank" class="action order">
                                            <span>Track Shipment</span>
                                        </a>
                                    <?php endif; ?>
                                <?php endforeach; ?>
                            <?php endif; ?>
                            <?php if ($viewModel->canCancel($_order->getEntityId())): ?>
                                <a href="#" class="cancel-order"
                                   id="cancel-order-<?=/* @noEscape */ $_order->getId() ?>" data-mage-init='{
                                       "cancelOrderModal":{
                                           "url": "<?=/* @noEscape */ $block->getBaseUrl(); ?>",
                                           "order_id": "<?= $block->escapeHtml(__($_order->getId())); ?>"
                                       }
                                    }'>
                                    <span><?= $block->escapeHtml(__('Cancel Order')) ?></span>
                                </a>
                                <div style="display: none;">
                                    <?= $this->getLayout()->createBlock("Magento\Framework\View\Element\Template")
                                        ->setOrder($_order)
                                        ->setReasons($viewModel->getCancellationReasons($_order->getEntityId()))
                                        ->setTemplate("Magento_OrderCancellationUi::cancel-order-modal.phtml")->toHtml()
                                    ?>
                                </div>
                            <?php endif ?>
                        <?php endif ?>
                    </td>
                </tr>
            <?php endforeach; ?>
            </tbody>
        </table>
    </div>
    <?php if ($block->getPagerHtml()) : ?>
        <div class="order-products-toolbar toolbar bottom"><?= $block->getPagerHtml() ?></div>
    <?php endif ?>
<?php else : ?>
    <div class="message info empty"><span><?= $block->escapeHtml($block->getEmptyOrdersMessage()) ?></span></div>
<?php endif ?>
