<?php
namespace SEO\GMC\Helper;

use Magento\Framework\App\Helper\AbstractHelper;
use Magento\Catalog\Api\ProductRepositoryInterface;
use Magento\Store\Model\StoreManagerInterface;
use Magento\CatalogInventory\Api\StockRegistryInterface;
use Magento\ConfigurableProduct\Model\Product\Type\Configurable;
use Magento\Framework\Pricing\PriceCurrencyInterface;
use Magento\UrlRewrite\Model\ResourceModel\UrlRewriteCollectionFactory;
use Magento\Framework\UrlInterface;
use Magento\Store\Model\ScopeInterface;
use Magento\Eav\Api\AttributeSetRepositoryInterface;
use Magento\Catalog\Model\Product\Attribute\Source\Status;
use Magento\InventorySalesApi\Api\GetProductSalableQtyInterface;
use Magento\InventorySalesApi\Api\StockResolverInterface;
use Magento\InventorySalesApi\Api\Data\SalesChannelInterface;
use Magento\ConfigurableProduct\Model\ResourceModel\Product\Type\Configurable as ConfigurableResource;

class GmcExportHelper extends AbstractHelper
{
    const TSV_FILE = 'gmc_product.tsv';

    protected $productRepository;
    protected $storeManager;
    protected $stockRegistry;
    protected $priceCurrency;
    protected $urlRewriteCollectionFactory;
    protected $attributeSetRepository;
    protected $salableQty;
    protected $stockResolver;
    protected $configurableResource;

    public function __construct(
        \Magento\Framework\App\Helper\Context $context,
        ProductRepositoryInterface $productRepository,
        StoreManagerInterface $storeManager,
        StockRegistryInterface $stockRegistry,
        PriceCurrencyInterface $priceCurrency,
        UrlRewriteCollectionFactory $urlRewriteCollectionFactory,
        AttributeSetRepositoryInterface $attributeSetRepository,
        GetProductSalableQtyInterface $salableQty,
        StockResolverInterface $stockResolver,
        ConfigurableResource $configurableResource
    ) {
        parent::__construct($context);
        $this->productRepository = $productRepository;
        $this->storeManager = $storeManager;
        $this->stockRegistry = $stockRegistry;
        $this->priceCurrency = $priceCurrency;
        $this->urlRewriteCollectionFactory = $urlRewriteCollectionFactory;
        $this->attributeSetRepository = $attributeSetRepository;
        $this->salableQty = $salableQty;
        $this->stockResolver = $stockResolver;
        $this->configurableResource = $configurableResource;
    }

    private function getSalableQty(string $sku, int $websiteId): float
    {
        try {
            $website = $this->storeManager->getWebsite($websiteId);

            $stock = $this->stockResolver->execute(
                SalesChannelInterface::TYPE_WEBSITE,
                $website->getCode()
            );

            return (float) $this->salableQty->execute($sku, (int) $stock->getStockId());
        } catch (\Exception $e) {
            return 0;
        }
    }

    private function attributeToString($value)
    {
        if (is_array($value)) {
            return implode(', ', array_filter($value));
        }
        return $value ? trim((string)$value) : '';
    }

    public function cleanText($text): string
    {
        if (!$text) return '';
        $text = preg_replace('#<style[^>]*>.*?</style>#is', '', $text);
        $text = strip_tags($text);
        $text = trim(preg_replace('/\s+/', ' ', $text));
        return mb_convert_encoding($text, 'UTF-8', 'UTF-8');
    }

    private function getCurrencyByWebsiteCode(string $websiteCode): string
    {
        return ($websiteCode === 'base') ? 'USD' : 'INR';
    }

    public function convertPriceCurrency(float $amount, int $storeId): float
    {
        try {
            return (float) $this->priceCurrency->convert($amount, $storeId);
        } catch (\Throwable $e) {
            return $amount;
        }
    }

    private function getStoreCurrencyCode(int $storeId): string
    {
        return $this->storeManager->getStore($storeId)->getCurrentCurrencyCode();
    }

    private function getMediaUrlPrefix($store)
    {
        return rtrim($store->getBaseUrl(UrlInterface::URL_TYPE_MEDIA), '/') . '/catalog/product';
    }

    private function isValidImage($file): bool
    {
        if (!$file) return false;
        return (strpos($file, 'placeholder') === false);
    }

    private function getParentCleanProductUrl(
    int $productId,
    int $storeId,
    array $params = []
    ): string {
        try {
            $store = $this->storeManager->getStore($storeId);

            $collection = $this->urlRewriteCollectionFactory->create()
                ->addFieldToFilter('entity_type', 'product')
                ->addFieldToFilter('entity_id', $productId)
                ->addFieldToFilter('store_id', $storeId)
                ->addFieldToFilter('redirect_type', 0)
                ->addFieldToFilter('is_autogenerated', 1)
                ->setPageSize(1)
                ->setOrder('url_rewrite_id', 'ASC');

            $rewrite = $collection->getFirstItem();

            if ($rewrite && $rewrite->getRequestPath()) {
                return $this->appendParams(
                    $store->getBaseUrl() . $rewrite->getRequestPath(),
                    $params
                );
            }

            $product = $this->productRepository->getById($productId, false, $storeId);

            if ($product->getUrlKey()) {
                $suffix = $this->scopeConfig->getValue(
                    'catalog/seo/product_url_suffix',
                    ScopeInterface::SCOPE_STORE
                ) ?: '.html';

                return $this->appendParams(
                    $store->getBaseUrl() . $product->getUrlKey() . $suffix,
                    $params
                );
            }

            // Fallback URL (catalog/product/view)
            return $store->getUrl(
                'catalog/product/view',
                array_merge(
                    [
                        'id'      => $productId,
                        '_store'  => $storeId,
                        '_nosid'  => true,
                    ],
                    array_filter($params)
                )
            );

        } catch (\Throwable $e) {
            return $this->storeManager->getStore()->getBaseUrl();
        }
    }

    /**
     * Append query parameters safely
     */
    private function appendParams(string $url, array $params): string
    {
        $params = array_filter($params);

        if (empty($params)) {
            return $url;
        }

        return $url . '?' . http_build_query($params);
    }

    public function loadExistingTsv(string $filePath): array
    {
        if (!file_exists($filePath)) return [];

        $rows = [];
        $fp = fopen($filePath, 'r');

        fgetcsv($fp, 0, "\t"); // skip header

        while ($data = fgetcsv($fp, 0, "\t")) {
            if (!isset($data[0])) continue; // ID column
            $rows[$data[0]] = $data;
        }

        fclose($fp);
        return $rows;
    }

    public function buildRow($product, int $websiteId): array
    {
        $rows = [];
        static $processedParents = [];

        // CONFIGURABLE PRODUCT
        if ($product->getTypeId() === Configurable::TYPE_CODE) {

            if (isset($processedParents[$product->getId()])) {
                return [];
            }

            $processedParents[$product->getId()] = true;

            $rows[] = $this->buildParentRow($product, $websiteId);

            $children = $product->getTypeInstance()->getUsedProducts($product);
            foreach ($children as $child) {
                $rows[] = $this->buildChildRow($product, $child, $websiteId);
            }

            return $rows;
        }

        // SIMPLE PRODUCT
        $parentIds = $this->configurableResource
            ->getParentIdsByChild((int) $product->getId());

        if (!empty($parentIds)) {

            // SIMPLE BELONGS TO CONFIGURABLE
            $parentId = (int) reset($parentIds);

            $parent = $this->productRepository->getById(
                $parentId,
                false,
                $this->storeManager
                    ->getWebsite($websiteId)
                    ->getDefaultStore()
                    ->getId()
            );

            $rows[] = $this->buildChildRow($parent, $product, $websiteId);

        } else {

            // STANDALONE SIMPLE PRODUCT
            $rows[] = $this->buildChildRow($product, $product, $websiteId);
        }

        return $rows;
    }

    public function buildParentRow($parent, int $websiteId): array
    {
        $store = $this->storeManager->getWebsite($websiteId)->getDefaultStore();
        $parent = $this->productRepository->getById(
            $parent->getId(),
            false,
            $store->getId()
        );

        // Parent must be enabled
        if ((int)$parent->getStatus() !== Status::STATUS_ENABLED) {
            return [];
        }

        // Must have at least ONE enabled + salable child (MSI-safe)
        $hasSalableChild = false;
        foreach ($parent->getTypeInstance()->getUsedProducts($parent) as $child) {
            if (
                (int)$child->getStatus() === Status::STATUS_ENABLED &&
                $this->getSalableQty($child->getSku(), $websiteId) > 0
            ) {
                $hasSalableChild = true;
                break;
            }
        }

       /* if (!$hasSalableChild) {
            return [];
        }*/

        $mediaUrl = $this->getMediaUrlPrefix($store);
        $currency = $this->getStoreCurrencyCode($store->getId());

        // Resolve price from parent or first priced child
        $finalPrice = (float)$parent->getFinalPrice();
        if ($finalPrice <= 0) {
            foreach ($parent->getTypeInstance()->getUsedProducts($parent) as $child) {
                $childPrice = (float)$child->getFinalPrice();
                if ($childPrice > 0) {
                    $finalPrice = $childPrice;
                    break;
                }
            }
        }

        if ($finalPrice <= 0) {
            return [];
        }

        $final = $this->convertPriceCurrency(
            $finalPrice,
            $store->getId()
        );

        $mainImage = $mediaUrl . $parent->getImage();

        $additionals = [];
        foreach ($parent->getMediaGalleryImages() as $img) {
            if (
                $img->getFile() !== $parent->getImage() &&
                $this->isValidImage($img->getFile())
            ) {
                $additionals[] = $mediaUrl . $img->getFile();
            }
        }

        $stockItem = $this->stockRegistry->getStockItem($parent->getId(),$websiteId);
        $qty = ($stockItem && (int)$stockItem->getQty() > 0)? (int)$stockItem->getQty(): 1;

        return [
            $parent->getSku(),
            $this->cleanText($parent->getName()),
            $this->cleanText($parent->getDescription()),
            'in_stock', // MSI validated already
            $parentUrl = $this->getParentCleanProductUrl($parent->getId(),$store->getId()),
            number_format($final, 2) . ' ' . $currency,
            '',
            $parent->getGtin() ?: '',
            '',
            $this->attributeToString($parent->getAttributeText('brand')),
            implode(', ', $additionals),
            'new',
            'no',
            $this->attributeToString(strtolower($parent?->getAttributeText('type_of_material') ?? '')),
            $this->attributeToString($parent?->getAttributeText('size') ?? ''),
            $this->attributeToString(strtolower($parent?->getAttributeText('gender') ?? '')) ?: '',
            $this->attributeToString(strtolower($parent?->getAttributeText('color') ?? '')),
            $this->attributeToString(strtolower($parent?->getAttributeText('age_group') ?? '')) ?: 'adult',
            $this->attributeToString($parent?->getGoogleProductCategory() ?? ''),
            $mainImage,
            $this->attributeToString($parent->getGoogleProductType()),
            $parent->getSku(),
            'yes',
            $qty
        ];
    }

    public function buildChildRow($parent, $child, int $websiteId): array
    {
        $store = $this->storeManager->getWebsite($websiteId)->getDefaultStore();
        $child = $this->productRepository->getById(
            $child->getId(),
            false,
            $store->getId()
        );

         $parent = $this->productRepository->getById(
            $parent->getId(),
            false,
            $store->getId()
        );

        // Must be enabled
        if ((int)$child->getStatus() !== Status::STATUS_ENABLED) {
            return [];
        }

        // MSI salable qty ONLY
        $salableQty = (int)$this->getSalableQty(
            $child->getSku(),
            $websiteId
        );

        /*if ($salableQty <= 0) {
            return [];
        }*/

        $mediaUrl = $this->getMediaUrlPrefix($store);
        
        $regular = (float)$child->getPrice();
        $final   = (float)$child->getFinalPrice();

        $regular = $this->convertPriceCurrency($regular, $store->getId());
        $final   = $this->convertPriceCurrency($final, $store->getId());

        $currency = $this->getStoreCurrencyCode($store->getId());

        $priceFormatted = number_format($regular, 2) . ' ' . $currency;
        $saleFormatted  = ($final < $regular)
            ? number_format($final, 2) . ' ' . $currency
            : '';

        $mainImage = $mediaUrl . $child->getImage();

        $additionals = [];
        foreach ($child->getMediaGalleryImages() as $img) {
            if (
                $img->getFile() !== $child->getImage() &&
                $this->isValidImage($img->getFile())
            ) {
                $additionals[] = $mediaUrl . $img->getFile();
            }
        }

        $childParams = [
            'size'     => strtolower($child->getAttributeText('size') ?? ''),
            'color'    => strtolower($child->getAttributeText('color') ?? ''),
            'material' => strtolower($child->getAttributeText('type_of_material') ?? ''),
        ];

        return [
            $child->getSku(),
            $this->cleanText($child->getName()),
            $this->cleanText($child->getDescription()),
            'in_stock', // MSI confirmed
            $this->getParentCleanProductUrl($parent->getId(),$store->getId()),
            $priceFormatted,
            $saleFormatted,
            $child->getGtin() ?: '',
            '',
            $this->attributeToString($child->getAttributeText('brand')),
            implode(', ', $additionals),
            'new',
            'no',
            $this->attributeToString(strtolower($child?->getAttributeText('type_of_material') ?? '')),
            $this->attributeToString($child?->getAttributeText('size') ?? ''),
            $this->attributeToString(strtolower($child?->getAttributeText('gender') ?? '')) ?: '',
            $this->attributeToString(strtolower($child?->getAttributeText('color') ?? '')),
            $this->attributeToString(strtolower($child?->getAttributeText('age_group') ?? '')) ?: 'adult',
            $this->attributeToString($child?->getGoogleProductCategory() ?? ''),
            $mainImage,
            $this->attributeToString($child->getGoogleProductType()),
            $parent->getSku(),
            'yes',
            $salableQty
        ];
    }

    public function writeTsv(string $filePath, array $rows): void
    {
        $header = [
            'id','title','description','availability','link',
            'price','sale price','gtin','mpn','brand',
            'additional_image_link','condition','adult','color','size','gender',
            'color','age group','google product category','image link',
            'product type','item group id','identifier exists','sell on google quantity'
        ];

        $fp = fopen($filePath, 'w');

        // BOM for UTF-8
        fwrite($fp, "\xEF\xBB\xBF");

        // Write header without quotes
        fwrite($fp, implode("\t", $header) . "\n");

        foreach ($rows as $row) {

            // Handle nested rows
            if (is_array($row) && isset($row[0]) && is_array($row[0])) {
                foreach ($row as $subRow) {
                    $clean = array_map([$this, 'sanitizeField'], $subRow);
                    fwrite($fp, implode("\t", $clean) . "\n");
                }
            } else {
                $clean = array_map([$this, 'sanitizeField'], $row);
                fwrite($fp, implode("\t", $clean) . "\n");
            }
        }

        fclose($fp);
    }

    private function sanitizeField($value)
    {
        if ($value === null) return '';

        // Remove tabs and newlines (GMC rejects them)
        $value = str_replace(["\t", "\r", "\n"], " ", $value);

        // Remove HTML
        $value = strip_tags($value);

        // Normalize whitespace
        $value = trim(preg_replace('/\s+/', ' ', $value));

        // Keep commas EXACTLY as entered (Google Sheet behavior)
        return $value;
    }
}
