<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var \Magento\Store\Block\Switcher $block */
$show_flags = $this->helper('Olegnax\Athlete2\Helper\Helper')->getConfig('athlete2_settings/footer/store_switch_flags');
?>
<?php if (count($block->getGroups())>1) : ?>
<div class="switcher store switcher-store tiny-drop tiny-arrow <?php if(!$show_flags){ echo ' noflags'; } ?>" id="switcher-store">
    <strong class="label switcher-label"><span><?= $block->escapeHtml(__('Select Store')) ?></span></strong>
    <div class="actions dropdown options switcher-options">
        <?php foreach ($block->getGroups() as $_group) : ?>
            <?php if ($_group->getId() == $block->getCurrentGroupId()) : ?>
                <div class="action toggle switcher-trigger"
                     role="button"
                     tabindex="0"
                     data-mage-init='{"dropdown":{"autoclose":"false"}}'
                     data-toggle="dropdown"
                     data-trigger-keypress-button="true"
                     id="switcher-store-trigger">
                     <strong class="view-<?= $block->escapeHtml($block->getCurrentStoreCode()) ?>">
                        <?php if($show_flags) { ?>
                        <img class="flag-image" src="<?= $block->escapeUrl($block->getViewFileUrl('images/flags/' . $_group->getCode() . '.png')) ?>" width="16px" height="12px" alt="<?= $block->escapeHtmlAttr($_group->getName()) ?>" />
                        <?php } ?>
                        <span class="flag-name"><?= $block->escapeHtml($_group->getName()) ?></span>
                    </strong>
                </div>
            <?php endif; ?>
        <?php endforeach; ?>
        <ul class="dropdown switcher-dropdown" data-target="dropdown">
            <?php foreach ($block->getGroups() as $_group) : ?>
                <?php if (!($_group->getId() == $block->getCurrentGroupId())) : ?>
                    <li class="switcher-option">
                        <a href="#" data-post='<?= /* @noEscape */ $block->getTargetStorePostData($_group->getDefaultStore()) ?>'>
                            <?php if($show_flags) { ?>
                            <img class="flag-image" src="<?= $block->escapeUrl($block->getViewFileUrl('images/flags/' . $_group->getCode() . '.png')) ?>" width="16px" height="12px" alt="<?= $block->escapeHtmlAttr($_group->getName()) ?>" />
                            <?php } ?>
                            <span class="flag-name"><?= $block->escapeHtml($_group->getName()) ?></span>
                        </a>
                    </li>
                <?php endif; ?>
            <?php endforeach; ?>
        </ul>
    </div>
</div>
<?php endif; ?>
