<?php
namespace Phonepe\PG\Model\Constants;

class EventConstants
{
    const CHANGES_SAVED_AND_PLUGIN_ACTIVATED        = 'CHANGES_SAVED_AND_PLUGIN_ACTIVATED';
    const PLUGIN_DEACTIVATED                        = 'PLUGIN_DEACTIVATED';
    const CALLBACK_RECIEVED_AT_PLUGIN               = 'CALLBACK_RECIEVED_AT_PLUGIN';
    const PAYMENT_REQUEST_TRIGGERED_FROM_PLUGIN     = 'PAYMENT_REQUEST_TRIGGERED_FROM_PLUGIN';
    const PAYMENT_RESPONSE_RECEIVED_AT_PLUGIN       = 'PAYMENT_RESPONSE_RECEIVED_AT_PLUGIN';
    const PLUGIN_HAS_GIVEN_CONTROL_BACK_TO_MERCHANT = 'PLUGIN_HAS_GIVEN_CONTROL_BACK_TO_MERCHANT';
    const PLUGIN_HAS_LAUNCHED_PAY_PAGE              = 'PLUGIN_HAS_LAUNCHED_PAY_PAGE';
    const PLUGIN_STATUS_CHECK                       = 'PLUGIN_STATUS_CHECK';
}
