<?php if ($block->getGstNumber()): ?>
<section class="admin__page-section order-view-account-information">
    <div class="admin__page-section-title">
        <span class="title">GST Information</span>
    </div>
    <div class="admin__page-section-content">
        <div class="admin__page-section-item order-information">
            <div class="admin__page-section-item-content">
                <table class="admin__table-secondary order-information-table">
                    <tbody>
                        <tr>
                            <th>GST Number:</th>
                            <td><?= $block->escapeHtml($block->getGstNumber()) ?></td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</section>
<?php endif; ?>